spring:
  datasource:
    url: jdbc:mysql:aws://localhost:3306/bb_products?zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: root
    driverClassName: software.aws.rds.jdbc.mysql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 30
      connectionTestQuery: select now() from dual
      connectionTimeout: 20000
      jdbc-url: jdbc:mysql:aws://localhost:3306/bb_products?zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
      username: root
      password: root
