spring:
  ws.products:
    clientId: ${API_CONNECT_CLIENT_ID}
    clientSecret: ${API_CONNECT_CLIENT_SECRET}

  datasource:
    url: jdbc:mysql:aws://localhost:3306/siebel?zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: root
    driverClassName: software.aws.rds.jdbc.mysql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 30
      connectionTestQuery: select now() from dual
      connectionTimeout: 20000
      jdbc-url: jdbc:mysql:aws://localhost:3306/siebel?zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
      username: root
      password: root

server:
  port: 8080
  servlet.context-path: /bb-products